# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import my_protobuf_pb2 as my__protobuf__pb2


class Image_parserStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.getImage = channel.unary_unary(
        '/playground.Image_parser/getImage',
        request_serializer=my__protobuf__pb2.ImageRequest.SerializeToString,
        response_deserializer=my__protobuf__pb2.ImageReply.FromString,
        )


class Image_parserServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def getImage(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_Image_parserServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'getImage': grpc.unary_unary_rpc_method_handler(
          servicer.getImage,
          request_deserializer=my__protobuf__pb2.ImageRequest.FromString,
          response_serializer=my__protobuf__pb2.ImageReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'playground.Image_parser', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
