# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: my_protobuf.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='my_protobuf.proto',
  package='playground',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x11my_protobuf.proto\x12\nplayground\"\x1c\n\x0cImageRequest\x12\x0c\n\x04\x46ile\x18\x01 \x01(\x0c\"\x1c\n\nImageReply\x12\x0e\n\x06result\x18\x01 \x01(\t2N\n\x0cImage_parser\x12>\n\x08getImage\x12\x18.playground.ImageRequest\x1a\x16.playground.ImageReply\"\x00\x62\x06proto3'
)




_IMAGEREQUEST = _descriptor.Descriptor(
  name='ImageRequest',
  full_name='playground.ImageRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='File', full_name='playground.ImageRequest.File', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=61,
)


_IMAGEREPLY = _descriptor.Descriptor(
  name='ImageReply',
  full_name='playground.ImageReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='playground.ImageReply.result', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=63,
  serialized_end=91,
)

DESCRIPTOR.message_types_by_name['ImageRequest'] = _IMAGEREQUEST
DESCRIPTOR.message_types_by_name['ImageReply'] = _IMAGEREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ImageRequest = _reflection.GeneratedProtocolMessageType('ImageRequest', (_message.Message,), {
  'DESCRIPTOR' : _IMAGEREQUEST,
  '__module__' : 'my_protobuf_pb2'
  # @@protoc_insertion_point(class_scope:playground.ImageRequest)
  })
_sym_db.RegisterMessage(ImageRequest)

ImageReply = _reflection.GeneratedProtocolMessageType('ImageReply', (_message.Message,), {
  'DESCRIPTOR' : _IMAGEREPLY,
  '__module__' : 'my_protobuf_pb2'
  # @@protoc_insertion_point(class_scope:playground.ImageReply)
  })
_sym_db.RegisterMessage(ImageReply)



_IMAGE_PARSER = _descriptor.ServiceDescriptor(
  name='Image_parser',
  full_name='playground.Image_parser',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=93,
  serialized_end=171,
  methods=[
  _descriptor.MethodDescriptor(
    name='getImage',
    full_name='playground.Image_parser.getImage',
    index=0,
    containing_service=None,
    input_type=_IMAGEREQUEST,
    output_type=_IMAGEREPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_IMAGE_PARSER)

DESCRIPTOR.services_by_name['Image_parser'] = _IMAGE_PARSER

# @@protoc_insertion_point(module_scope)
