# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import my_protobuf_pb2 as my__protobuf__pb2


class transactionTestStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.IimageOtext = channel.unary_unary(
        '/playground.transactionTest/IimageOtext',
        request_serializer=my__protobuf__pb2.ImageType.SerializeToString,
        response_deserializer=my__protobuf__pb2.ImageType.FromString,
        )


class transactionTestServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def IimageOtext(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_transactionTestServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'IimageOtext': grpc.unary_unary_rpc_method_handler(
          servicer.IimageOtext,
          request_deserializer=my__protobuf__pb2.ImageType.FromString,
          response_serializer=my__protobuf__pb2.ImageType.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'playground.transactionTest', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
