# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import my_protobuf_pb2 as my__protobuf__pb2


class transactionTestStub(object):
    """Missing associated documentation comment in .proto file"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.IimageOimage = channel.unary_unary(
                '/playground.transactionTest/IimageOimage',
                request_serializer=my__protobuf__pb2.ImageType.SerializeToString,
                response_deserializer=my__protobuf__pb2.ImageType.FromString,
                )
        self.ItextOtext = channel.unary_unary(
                '/playground.transactionTest/ItextOtext',
                request_serializer=my__protobuf__pb2.TextType.SerializeToString,
                response_deserializer=my__protobuf__pb2.TextType.FromString,
                )
        self.IjsonOjson = channel.unary_unary(
                '/playground.transactionTest/IjsonOjson',
                request_serializer=my__protobuf__pb2.JSONType.SerializeToString,
                response_deserializer=my__protobuf__pb2.JSONType.FromString,
                )


class transactionTestServicer(object):
    """Missing associated documentation comment in .proto file"""

    def IimageOimage(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ItextOtext(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IjsonOjson(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_transactionTestServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'IimageOimage': grpc.unary_unary_rpc_method_handler(
                    servicer.IimageOimage,
                    request_deserializer=my__protobuf__pb2.ImageType.FromString,
                    response_serializer=my__protobuf__pb2.ImageType.SerializeToString,
            ),
            'ItextOtext': grpc.unary_unary_rpc_method_handler(
                    servicer.ItextOtext,
                    request_deserializer=my__protobuf__pb2.TextType.FromString,
                    response_serializer=my__protobuf__pb2.TextType.SerializeToString,
            ),
            'IjsonOjson': grpc.unary_unary_rpc_method_handler(
                    servicer.IjsonOjson,
                    request_deserializer=my__protobuf__pb2.JSONType.FromString,
                    response_serializer=my__protobuf__pb2.JSONType.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'playground.transactionTest', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class transactionTest(object):
    """Missing associated documentation comment in .proto file"""

    @staticmethod
    def IimageOimage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/playground.transactionTest/IimageOimage',
            my__protobuf__pb2.ImageType.SerializeToString,
            my__protobuf__pb2.ImageType.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ItextOtext(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/playground.transactionTest/ItextOtext',
            my__protobuf__pb2.TextType.SerializeToString,
            my__protobuf__pb2.TextType.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def IjsonOjson(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/playground.transactionTest/IjsonOjson',
            my__protobuf__pb2.JSONType.SerializeToString,
            my__protobuf__pb2.JSONType.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
