# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: my_protobuf.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='my_protobuf.proto',
  package='playground',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x11my_protobuf.proto\x12\nplayground\")\n\tImageType\x12\x0e\n\x06\x66ormat\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\"\x18\n\x08TextType\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\"\x18\n\x08JSONType\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x32\xc9\x01\n\x0ftransactionTest\x12>\n\x0cIimageOimage\x12\x15.playground.ImageType\x1a\x15.playground.ImageType\"\x00\x12:\n\nItextOtext\x12\x14.playground.TextType\x1a\x14.playground.TextType\"\x00\x12:\n\nIjsonOjson\x12\x14.playground.JSONType\x1a\x14.playground.JSONType\"\x00\x62\x06proto3'
)




_IMAGETYPE = _descriptor.Descriptor(
  name='ImageType',
  full_name='playground.ImageType',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='format', full_name='playground.ImageType.format', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='playground.ImageType.data', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=74,
)


_TEXTTYPE = _descriptor.Descriptor(
  name='TextType',
  full_name='playground.TextType',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='playground.TextType.data', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=76,
  serialized_end=100,
)


_JSONTYPE = _descriptor.Descriptor(
  name='JSONType',
  full_name='playground.JSONType',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='playground.JSONType.data', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=102,
  serialized_end=126,
)

DESCRIPTOR.message_types_by_name['ImageType'] = _IMAGETYPE
DESCRIPTOR.message_types_by_name['TextType'] = _TEXTTYPE
DESCRIPTOR.message_types_by_name['JSONType'] = _JSONTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ImageType = _reflection.GeneratedProtocolMessageType('ImageType', (_message.Message,), {
  'DESCRIPTOR' : _IMAGETYPE,
  '__module__' : 'my_protobuf_pb2'
  # @@protoc_insertion_point(class_scope:playground.ImageType)
  })
_sym_db.RegisterMessage(ImageType)

TextType = _reflection.GeneratedProtocolMessageType('TextType', (_message.Message,), {
  'DESCRIPTOR' : _TEXTTYPE,
  '__module__' : 'my_protobuf_pb2'
  # @@protoc_insertion_point(class_scope:playground.TextType)
  })
_sym_db.RegisterMessage(TextType)

JSONType = _reflection.GeneratedProtocolMessageType('JSONType', (_message.Message,), {
  'DESCRIPTOR' : _JSONTYPE,
  '__module__' : 'my_protobuf_pb2'
  # @@protoc_insertion_point(class_scope:playground.JSONType)
  })
_sym_db.RegisterMessage(JSONType)



_TRANSACTIONTEST = _descriptor.ServiceDescriptor(
  name='transactionTest',
  full_name='playground.transactionTest',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=129,
  serialized_end=330,
  methods=[
  _descriptor.MethodDescriptor(
    name='IimageOimage',
    full_name='playground.transactionTest.IimageOimage',
    index=0,
    containing_service=None,
    input_type=_IMAGETYPE,
    output_type=_IMAGETYPE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ItextOtext',
    full_name='playground.transactionTest.ItextOtext',
    index=1,
    containing_service=None,
    input_type=_TEXTTYPE,
    output_type=_TEXTTYPE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='IjsonOjson',
    full_name='playground.transactionTest.IjsonOjson',
    index=2,
    containing_service=None,
    input_type=_JSONTYPE,
    output_type=_JSONTYPE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_TRANSACTIONTEST)

DESCRIPTOR.services_by_name['transactionTest'] = _TRANSACTIONTEST

# @@protoc_insertion_point(module_scope)
